import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { UserContextProvider } from '@/context/useContext';
import { SkeletonTheme } from 'react-loading-skeleton';
import 'react-loading-skeleton/dist/skeleton.css';
import Providers from '@/app/providers';
import { isAuthenticated } from '@/utils/api/isAuthenticated';

const nunitoSans = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthencated = await isAuthenticated();

  return (
    <html lang="en">
      <body className={`${nunitoSans.variable} font-main  antialiased`}>
        <Providers>
          <UserContextProvider isAuthencated={!!isAuthencated}>
            <SkeletonTheme baseColor="#f5f5f5" highlightColor="#fafafa">
              {children}
            </SkeletonTheme>
          </UserContextProvider>
        </Providers>

        <Toaster
          toastOptions={{
            classNames: {
              error: 'bg-primary-500',
            },
          }}
          richColors
          closeButton={true}
          position={'top-right'}
        />
      </body>
    </html>
  );
}
